// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuvUI0fVIrMlTvXsuK48kMo8vZ8Wos0Rg',
    appId: '1:276311580922:android:04aee17189e404a53de943',
    messagingSenderId: '276311580922',
    projectId: 'uni-of-madinah-9e99b',
    storageBucket: 'uni-of-madinah-9e99b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYbXEp3I4yJVGusMDHEwIsqtVUOupewt4',
    appId: '1:276311580922:ios:479f76c80191c3ac3de943',
    messagingSenderId: '276311580922',
    projectId: 'uni-of-madinah-9e99b',
    storageBucket: 'uni-of-madinah-9e99b.appspot.com',
    androidClientId: '276311580922-fnfeu3bncn5irlsmgo28ua9n9ilmo2b6.apps.googleusercontent.com',
    iosClientId: '276311580922-3ar1bitl5ogrj68bm9che5r2ddafntuh.apps.googleusercontent.com',
    iosBundleId: 'com.example.uniOfMadinah',
  );
}
